config/routes.rb
Smads::Application.routes.draw do
  resources :broadcasts, :only => [:show, :index, :create, :new]

  resources :subscribers do
    collection do
      get :broadcast
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base
  attr_accessible :message
end

app/models/mobile.rb
class Mobile 
  include HTTParty
  base_uri 'api.tropo.com'
  
  def send_sms(number, message)
    token = "155cfd2913673d4aac374e1e9ade2ea38e89662e5640034aa2e7db98e63b1f9052b57fab1f89f9e707bda8c7"
    self.class.get("/1.0/sessions?action=create&token=#{token}&numberToDial=#{number}&msg=#{message}")
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :name, :number
  
  belongs_to :user
  
  def send_message(message)
    mobile = Mobile.new
    mobile.send_sms self.number, message
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  has_many :subscribers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  before_filter :authenticate_user!
  # GET /broadcasts
  # GET /broadcasts.json
  def index
    @broadcasts = Broadcast.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @broadcasts }
    end
  end

  # GET /broadcasts/1
  # GET /broadcasts/1.json
  def show
    @broadcast = Broadcast.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @broadcast }
    end
  end

  # GET /broadcasts/new
  # GET /broadcasts/new.json
  def new
    @broadcast = Broadcast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @broadcast }
    end
  end

  # POST /broadcasts
  # POST /broadcasts.json
  def create
    @broadcast = Broadcast.new(params[:broadcast])
    current_user.subscribers.each do |subscriber|
      subscriber.send_message(@broadcast.message)
    end
    
    respond_to do |format|
      if @broadcast.save
        format.html { redirect_to @broadcast, notice: 'Broadcast was successfully created.' }
        format.json { render json: @broadcast, status: :created, location: @broadcast }
      else
        format.html { render action: "new" }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_filter :authenticate_user!
  
  # POST /subscribers/broadcast
  # POST /subscribers/broadcast.json
  def broadcast
    mobile = Mobile.new
    current_user.subscribers
    current_user.subscribers.each do |subscriber|
      mobile.send_sms(subscriber.number)
    end
    
    respond_to do |format|
      format.html { redirect_to action: :index} # index.html.erb
      format.json { render json: @subscribers }
    end
  end
  
  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = current_user.subscribers.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = current_user.subscribers.new(params[:subscriber])

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { render action: "new" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/broadcasts/_form.html.haml
= simple_form_for(@broadcast) do |f|
  = f.error_notification

  .form-inputs
    = f.input :message

  .form-actions
    = f.button :submit

app/views/broadcasts/edit.html.haml
%h1 Editing broadcast

= render 'form'

= link_to 'Show', @broadcast
\|
= link_to 'Back', broadcasts_path

app/views/broadcasts/index.html.haml
%h1 Listing broadcasts

%table
  %tr
    %th Message
    %th
    %th
    %th

  - @broadcasts.each do |broadcast|
    %tr
      %td= broadcast.message
      %td= link_to 'Show', broadcast

%br

= link_to 'New Broadcast', new_broadcast_path

app/views/broadcasts/new.html.haml
%h1 New broadcast

= render 'form'

= link_to 'Back', broadcasts_path

app/views/broadcasts/show.html.haml
%p
  %b Message:
  = @broadcast.message

= link_to 'Back', broadcasts_path

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Smads", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    %li
      = link_to 'Subscribers', subscribers_path
      
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
<!doctype html>
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Smads"
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/subscribers/_form.html.haml
= simple_form_for(@subscriber) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :number

  .form-actions
    = f.button :submit

app/views/subscribers/edit.html.haml
%h1 Editing subscriber

= render 'form'

= link_to 'Show', @subscriber
\|
= link_to 'Back', subscribers_path

app/views/subscribers/index.html.haml
%h1 Listing subscribers

%table
  %tr
    %th Name
    %th Number
    %th
    %th
    %th

  - @subscribers.each do |subscriber|
    %tr
      %td= subscriber.name
      %td= subscriber.number
      %td= link_to 'Show', subscriber
      %td= link_to 'Edit', edit_subscriber_path(subscriber)
      %td= link_to 'Destroy', subscriber, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Subscriber', new_subscriber_path
= link_to 'Broadcasts', broadcasts_path

app/views/subscribers/new.html.haml
%h1 New subscriber

= render 'form'

= link_to 'Back', subscribers_path

app/views/subscribers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @subscriber.name
%p
  %b Number:
  = @subscriber.number

= link_to 'Edit', edit_subscriber_path(@subscriber)
\|
= link_to 'Back', subscribers_path

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}